---
- hosts: localhost
  collections:
  - fortinet.fortios
  vars:
   host: "192.168.122.182"
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configureglobalattributes
    fortios_system_global:
      host:  "{{ host }}"
      vdom:  "{{ vdom }}"
      https: "True"
      ssl_verify:  "{{ ssl_verify }}"
      system_global:
        admintimeout: "23"
        hostname: "FortiGate02"
