---
- hosts: localhost
  collections:
  - fortinet.fortios.fortios_system_automation_action
  vars:
   host: "192.168.122.182"
   username: "admin"
   password: "abc123"
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      ssl_verify:  "{{ ssl_verify }}"
      system_global:
        admintimeout: "23"
        hostname: "FortiGate02"
